# Generated by Django 5.2.16 on 2026-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer / Adopter'), ('SHELTER', 'Shelter'), ('DELIVERY', 'Delivery Staff'), ('VETERINARIAN', 'Veterinarian')], default='CUSTOMER', max_length=20),
        ),
    ]
