# Generated by Django 6.1.1 on 2026-09-29 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('REGISTRATION', 'Shelter Registration / Proof'), ('GOVERNMENT_ID', 'Government / Identity Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('AUTHORIZATION', 'Authorization Document'), ('ADOPTION_CERT', 'Adoption-Related Certification'), ('OTHER', 'Other Required Document')], default='OTHER', max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='shelter_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Documents Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_shelter_docs', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.shelterprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_shelter_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
