# Generated by Django 6.1.1 on 2026-09-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_shelter_document_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
