# Generated by Django 6.1.1 on 2026-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofile_postal_code_userprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterprofile',
            name='address',
            field=models.CharField(default='Panampilly Nagar', max_length=255),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='city',
            field=models.CharField(default='Kochi', max_length=100),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='shelter_logos/'),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='shelter_type',
            field=models.CharField(default='Animal Rescue & Rehabilitation Center', max_length=100),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
    ]
