# Generated by Django 6.1.1 on 2026-10-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_shelterprofile_address_shelterprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, default='123456', max_length=128, null=True),
        ),
    ]
