# Generated by Django 5.2.16 on 2026-08-17 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('DELIVERY_SCHEDULED', 'Delivery Scheduled'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_adoption_requests', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_adoption_requests', to='users.shelterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField()),
                ('preferred_date', models.DateField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Pet Picked Up'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived at Destination'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=20)),
                ('proof_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adoption_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='pets.adoptionrequest')),
                ('delivery_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(default='ADOPTION_AND_DELIVERY', max_length=50)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('adoption_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pets.adoptionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=True)),
                ('is_neutered', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING_ADOPTION', 'Pending Adoption'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20)),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_pets', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='users.shelterprofile')),
            ],
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet'),
        ),
        migrations.CreateModel(
            name='FavoritePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
            ],
            options={
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
