# Generated by Django 5.2.16 on 2026-08-21 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_id', models.CharField(default='HUB-101', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('manager_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='delivery_staff',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='distance_fee',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pet_transport_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='priority',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='special_handling_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=1100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='drop_address',
            field=models.TextField(default='Adopter Address'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_address',
            field=models.TextField(default='Shelter Address'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('ADOPTION_APPROVED', 'Adoption Approved'), ('DELIVERY_REQUESTED', 'Delivery Requested'), ('ELIGIBILITY_CHECKED', 'Eligibility Checked'), ('DELIVERY_CREATED', 'Delivery Created'), ('SCHEDULED', 'Delivery Scheduled'), ('PARTNER_ASSIGNED', 'Partner Assigned'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PET_READY', 'Pet Ready for Pickup'), ('PICKUP_CONFIRMED', 'Pickup Confirmed'), ('PET_PICKED_UP', 'Pet Picked Up'), ('ORIGIN_HUB', 'Origin Hub / Transport Center'), ('IN_TRANSIT', 'In Transit'), ('DESTINATION_HUB', 'Destination Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('NEAR_DESTINATION', 'Near Destination'), ('ARRIVED', 'Arrived at Destination'), ('HANDOVER_PENDING', 'Handover Verification Pending'), ('COMPLETED', 'Delivery Completed'), ('FAILED', 'Failed Delivery'), ('CANCELLED', 'Cancelled')], default='IN_TRANSIT', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(default='DP-1001', max_length=50, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(default='Pet Taxi Van', max_length=50)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('license_verified', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=4.8, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to='pets.deliverypartner'),
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='pets.deliveryrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandoverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='4892', max_length=10)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('digital_signature_data', models.TextField(blank=True, null=True)),
                ('photo_proof_url', models.URLField(blank=True, max_length=500, null=True)),
                ('handover_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_verification', to='pets.deliveryrequest')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='destination_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_deliveries', to='pets.transporthub'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='origin_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_deliveries', to='pets.transporthub'),
        ),
    ]
