# Generated by Django 5.2.16 on 2026-08-22 07:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_transporthub_remove_deliveryrequest_delivery_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=3500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=1100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_ref',
            field=models.CharField(default='pay_NxF928172635', max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_gateway',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(default='UPI / GooglePay', max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'No Refund'), ('INITIATED', 'Refund Initiated'), ('COMPLETED', 'Refund Completed'), ('FAILED', 'Refund Failed')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=4600.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default='TXN-2026-1001', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='SUCCESSFUL', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='SUCCESSFUL', max_length=25),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_role', models.CharField(default='Admin', max_length=50)),
                ('action', models.CharField(choices=[('ADOPTION_SUBMITTED', 'Adoption Request Submitted'), ('REQUEST_REVIEWED', 'Request Moved to Review'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_SUCCESSFUL', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_PROCESSED', 'Refund Processed'), ('DRIVER_ASSIGNED', 'Delivery Driver Assigned'), ('PET_PICKED_UP', 'Pet Picked Up from Shelter'), ('PET_DELIVERED', 'Pet Delivered to Adopter'), ('ADOPTION_COMPLETED', 'Adoption Completed'), ('REQUEST_CANCELLED', 'Request Cancelled')], default='ADOPTION_SUBMITTED', max_length=50)),
                ('module', models.CharField(default='Adoption Requests', max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True)),
                ('new_status', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=45)),
                ('device_info', models.CharField(default='Chrome 122.0 (Windows 11)', max_length=150)),
                ('description', models.TextField()),
                ('adoption_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pets.adoptionrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pets.paymenttransaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
