# Generated by Django 5.2.16 on 2026-09-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_paymenttransaction_amount_and_more'),
        ('users', '0003_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_partners', to='users.shelterprofile'),
        ),
    ]
