# Generated by Django 6.1.1 on 2026-09-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_deliverypartner_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('READY_FOR_HANDOVER', 'Ready for Handover'), ('DELIVERY_SCHEDULED', 'Delivery Scheduled'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25),
        ),
    ]
