# Generated by Django 6.1.1 on 2026-09-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_adoptionrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('ADOPTION_APPROVED', 'Adoption Approved'), ('DELIVERY_REQUESTED', 'Delivery Requested'), ('ELIGIBILITY_CHECKED', 'Eligibility Checked'), ('DELIVERY_CREATED', 'Delivery Created'), ('SCHEDULED', 'Delivery Scheduled'), ('PARTNER_ASSIGNED', 'Partner Assigned'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PET_READY', 'Pet Ready for Pickup'), ('PICKUP_CONFIRMED', 'Pickup Confirmed'), ('PET_PICKED_UP', 'Pet Picked Up'), ('ORIGIN_HUB', 'Origin Hub / Transport Center'), ('IN_TRANSIT', 'In Transit'), ('DESTINATION_HUB', 'Destination Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('NEAR_DESTINATION', 'Near Destination'), ('ARRIVED', 'Arrived at Destination'), ('HANDOVER_PENDING', 'Handover Verification Pending'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Delivery Completed'), ('FAILED', 'Failed Delivery'), ('CANCELLED', 'Cancelled')], default='UNASSIGNED', max_length=30),
        ),
    ]
