# Generated by Django 6.1.1 on 2026-09-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_deliveryrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
