# Generated by Django 6.1.1 on 2026-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_deliveryrequest_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
    ]
