# Generated by Django 6.1.1 on 2026-10-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_deliverypartner_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='appointment_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='appointment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='appointment_status',
            field=models.CharField(default='SCHEDULED', max_length=30),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='appointment_time',
            field=models.CharField(blank=True, default='11:00 AM', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='reschedule_requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='reschedule_requested_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
